# Generated by Django 5.1.5 on 2025-03-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
