# Generated by Django 5.1.5 on 2025-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_like_unique_together_alter_like_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
    ]
