# Generated by Django 5.1.5 on 2025-03-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_user_password'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'author')},
        ),
    ]
