# Generated by Django 5.1.5 on 2025-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_privacy_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('guest', 'Guest'), ('user', 'Regular User')], default='user', max_length=10),
        ),
    ]
